import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/SessionProvider'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/lib/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"
    className={(inter.className, "dark")}
    style={{
      colorScheme: "dark",
    }}
    >
      <body>
        <AuthProvider>
    <ThemeProvider>
    <div
                 className="
                 flex
                 min-h-screen
                 w-full
                 flex-col
                 items-center
                 dark:bg-black"
          >

          <Navbar />
        <main className="flex flex-grow w-full justify-center items-center dark:bg-neutral-950">
        {children}
         </main>
         </div>
    </ThemeProvider>
        </AuthProvider>
        </body>
    </html>
  )
}
